# Generated by Django 3.2.1 on 2021-05-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user_image/kaizoku_man.png', upload_to='user_image'),
        ),
    ]
