# Generated by Django 3.2.1 on 2021-05-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
