# Generated by Django 3.2 on 2021-04-29 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='lose_point',
        ),
        migrations.RemoveField(
            model_name='result',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='result',
            name='win_point',
        ),
        migrations.AddField(
            model_name='result',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='result',
            name='player1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='player1_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='player1_deck',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='player1_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='player1_skill',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='player2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='player2_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='player2_deck',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='result',
            name='player2_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='player2_skill',
            field=models.CharField(default='', max_length=20),
        ),
    ]
