# Generated by Django 3.2 on 2021-04-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210429_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='player1_comment',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='player1',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='player1_deck',
            new_name='player',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='player1_point',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='player1_skill',
            new_name='skill',
        ),
        migrations.RemoveField(
            model_name='result',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='player2_comment',
        ),
        migrations.RemoveField(
            model_name='result',
            name='player2_deck',
        ),
        migrations.RemoveField(
            model_name='result',
            name='player2_point',
        ),
        migrations.RemoveField(
            model_name='result',
            name='player2_skill',
        ),
    ]
