# Generated by Django 3.2 on 2021-04-29 15:19

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_result_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player1', models.ManyToManyField(related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ManyToManyField(related_name='player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
