# Generated by Django 3.2 on 2021-04-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_result_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
    ]
