# Generated by Django 3.2 on 2021-04-29 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_remove_match_player2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='player1', to=settings.AUTH_USER_MODEL),
        ),
    ]
