# Generated by Django 3.2 on 2021-04-29 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210430_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='deck',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.deckthema'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
                ('character', models.ManyToManyField(to='app.Character')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='character',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.character'),
        ),
        migrations.AlterField(
            model_name='result',
            name='skill',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.skill'),
        ),
    ]
