# Generated by Django 3.2 on 2021-04-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_character_world'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='world',
            field=models.IntegerField(choices=[(1, 'DM'), (2, 'DSOD'), (3, 'GX'), (4, "5D's"), (5, 'ZEXAL')]),
        ),
    ]
