# Generated by Django 3.2 on 2021-05-02 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0025_auto_20210502_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='comment1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='comment2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='deck1',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='deck1', to='app.deckthema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='deck2',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='deck2', to='app.deckthema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='point1',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='point2',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='skill1',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='skill1', to='app.skill'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='skill2',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='skill2', to='app.skill'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
