# Generated by Django 3.2 on 2021-05-02 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_delete_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='comment1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='comment2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='deck1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deck1', to='app.deckthema'),
        ),
        migrations.AlterField(
            model_name='match',
            name='deck2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deck2', to='app.deckthema'),
        ),
        migrations.AlterField(
            model_name='match',
            name='point1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='point2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='skill1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill1', to='app.skill'),
        ),
        migrations.AlterField(
            model_name='match',
            name='skill2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill2', to='app.skill'),
        ),
    ]
