# Generated by Django 3.2 on 2021-05-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210502_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match1_1',
            field=models.IntegerField(choices=[(1, 'W'), (2, 'L'), (1, 'DCW'), (0, 'DCL')], default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='match1_2',
            field=models.IntegerField(choices=[(1, 'W'), (2, 'L'), (1, 'DCW'), (0, 'DCL')], default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='match1_3',
            field=models.IntegerField(choices=[(1, 'W'), (2, 'L'), (1, 'DCW'), (0, 'DCL')], default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='match2_1',
            field=models.IntegerField(choices=[(1, 'W'), (2, 'L'), (1, 'DCW'), (0, 'DCL')], default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='match2_2',
            field=models.IntegerField(choices=[(1, 'W'), (2, 'L'), (1, 'DCW'), (0, 'DCL')], default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='match2_3',
            field=models.IntegerField(choices=[(1, 'W'), (2, 'L'), (1, 'DCW'), (0, 'DCL')], default=0),
        ),
    ]
