# Generated by Django 3.2 on 2021-05-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210502_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match1_1',
            field=models.IntegerField(blank=True, choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='match1_2',
            field=models.IntegerField(blank=True, choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='match1_3',
            field=models.IntegerField(blank=True, choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match2_1',
            field=models.IntegerField(blank=True, choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='match2_2',
            field=models.IntegerField(blank=True, choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='match2_3',
            field=models.IntegerField(blank=True, choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')], null=True),
        ),
    ]
