# Generated by Django 3.2 on 2021-05-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210502_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='deck1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deck1', to='app.deckthema'),
        ),
        migrations.AlterField(
            model_name='match',
            name='deck2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deck2', to='app.deckthema'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match1_1',
            field=models.IntegerField(choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match1_2',
            field=models.IntegerField(choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match2_1',
            field=models.IntegerField(choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match2_2',
            field=models.IntegerField(choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')], null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='point1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='point2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='skill1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill1', to='app.skill'),
        ),
        migrations.AlterField(
            model_name='match',
            name='skill2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skill2', to='app.skill'),
        ),
    ]
