# Generated by Django 3.2 on 2021-05-02 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0033_auto_20210502_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result1', models.IntegerField(choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')])),
                ('result2', models.IntegerField(choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')])),
                ('result3', models.IntegerField(choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')])),
                ('point', models.IntegerField()),
                ('comment', models.TextField(blank=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.deckthema')),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='comment1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='comment2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='deck1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='deck2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match1_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match1_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match1_3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match2_1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match2_2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match2_3',
        ),
        migrations.RemoveField(
            model_name='match',
            name='point1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='point2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='skill1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='character',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.AddField(
            model_name='result',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.match'),
        ),
        migrations.AddField(
            model_name='result',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.skill'),
        ),
    ]
