# Generated by Django 3.2 on 2021-05-02 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0034_auto_20210503_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.match'),
        ),
        migrations.AlterField(
            model_name='result',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='result3',
            field=models.IntegerField(blank=True, choices=[(1, 'W'), (0, 'L'), (1, 'DCW'), (0, 'DCL')], null=True),
        ),
    ]
