# Generated by Django 3.2 on 2021-05-02 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0035_auto_20210503_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.match'),
        ),
        migrations.AlterField(
            model_name='result',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
