# Generated by Django 3.2 on 2021-05-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_result_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result1',
            field=models.IntegerField(choices=[(1, 'W'), (-1, 'L')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='result2',
            field=models.IntegerField(choices=[(1, 'W'), (-1, 'L')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='result3',
            field=models.IntegerField(blank=True, choices=[(1, 'W'), (-1, 'L')], null=True),
        ),
    ]
