# Generated by Django 3.2 on 2021-05-02 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0040_auto_20210503_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedeck',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='decks'),
        ),
        migrations.AlterField(
            model_name='usedeck',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.match'),
        ),
        migrations.AlterField(
            model_name='usedeck',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
