# Generated by Django 3.2 on 2021-05-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20210504_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='point',
        ),
        migrations.AlterField(
            model_name='result',
            name='result1',
            field=models.CharField(choices=[('W', 'Win'), ('L', 'Lose')], max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='result2',
            field=models.CharField(choices=[('W', 'Win'), ('L', 'Lose')], max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='result3',
            field=models.CharField(blank=True, choices=[('W', 'Win'), ('L', 'Lose')], max_length=10, null=True),
        ),
    ]
