# Generated by Django 3.2 on 2021-05-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20210504_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result1',
            field=models.IntegerField(choices=[(1, 'Win'), (-1, 'Lose'), (0, 'None')], max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='result2',
            field=models.IntegerField(choices=[(1, 'Win'), (-1, 'Lose'), (0, 'None')], max_length=10),
        ),
        migrations.AlterField(
            model_name='result',
            name='result3',
            field=models.IntegerField(choices=[(1, 'Win'), (-1, 'Lose'), (0, 'None')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
