# Generated by Django 3.2 on 2021-05-04 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0048_result_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='result1',
            field=models.IntegerField(choices=[(1, 'Win'), (-1, 'Lose'), (0, 'None')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='result2',
            field=models.IntegerField(choices=[(1, 'Win'), (-1, 'Lose'), (0, 'None')]),
        ),
        migrations.AlterField(
            model_name='result',
            name='result3',
            field=models.IntegerField(choices=[(1, 'Win'), (-1, 'Lose'), (0, 'None')]),
        ),
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results1', models.JSONField()),
                ('point1', models.IntegerField()),
                ('score1', models.IntegerField()),
                ('results2', models.JSONField()),
                ('point2', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('deck1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck1', to='app.deckthema')),
                ('deck2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck2', to='app.deckthema')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.match')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name2', to=settings.AUTH_USER_MODEL)),
                ('skill1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill1', to='app.skill')),
                ('skill2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill2', to='app.skill')),
            ],
        ),
    ]
