# Generated by Django 3.2 on 2021-05-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_auto_20210504_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedeck',
            name='submit_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DeckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.match')),
                ('thema1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thema1', to='app.deckthema')),
                ('thema2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thema2', to='app.deckthema')),
            ],
        ),
    ]
